cxx_library(
    name = "prime_utils",
    header_namespace = 'utils',
    srcs = [
        "prime_utils.cpp",
    ],
    exported_headers = [
        "prime_utils.h",
    ],
    visibility = [
        "//...",
    ],
)

cxx_library(
    name = "string_utils",
    header_namespace = 'utils',
    srcs = [
        "string_utils.cpp",
    ],
    exported_headers = [
        "string_utils.h",
    ],
    visibility = [
        "//...",
    ],
)
