cxx_binary(
    name = "p1",
    srcs = [
        "p1.cpp",
    ],
)

cxx_binary(
    name = "p2",
    srcs = [
        "p2.cpp",
    ],
)

cxx_binary(
    name = "p3",
    srcs = [
        "p3.cpp",
    ],
    deps = [
        "//src/utils:prime_utils",
    ],
)

cxx_binary(
    name = "p4",
    srcs = [
        "p4.cpp",
    ],
)
