cxx_binary(
    name = "p1",
    srcs = [
        "p0001.cpp",
    ],
)

cxx_binary(
    name = "p2",
    srcs = [
        "p0002.cpp",
    ],
)

cxx_binary(
    name = "p3",
    srcs = [
        "p0003.cpp",
    ],
    deps = [
        "//src/utils:prime_utils",
    ],
)

cxx_binary(
    name = "p4",
    srcs = [
        "p0004.cpp",
    ],
)

cxx_binary(
    name = "p5",
    srcs = [
        "p0005.cpp",
    ],
)

cxx_binary(
    name = "p6",
    srcs = [
        "p0006.cpp",
    ],
)

cxx_binary(
    name = "p7",
    srcs = [
        "p0007.cpp",
    ],
    deps = [
        "//src/utils:prime_utils",
    ],
)

cxx_binary(
    name = "p8",
    srcs = [
        "p0008.cpp",
    ],
)

cxx_binary(
    name = "p9",
    srcs = [
        "p0009.cpp",
    ],
)

cxx_binary(
    name = "p10",
    srcs = [
        "p0010.cpp",
    ],
    deps = [
        "//src/utils:prime_utils",
    ],
)

cxx_binary(
    name = "p11",
    srcs = [
        "p0011.cpp",
    ],
    deps = [
        "//src/utils:string_utils",
    ]
)

cxx_binary(
    name = "p12",
    srcs = [
        "p0012.cpp",
    ],
    deps = [
        "//src/utils:prime_utils",
    ],
)


cxx_binary(
    name = "p14",
    srcs = [
        "p0014.cpp",
    ],
)
